/**
 * School display names for the valid 2026 NCAAF registry and published slates.
 * Keys remain the existing ESPN/feed identities; names are explicit school
 * labels with abbreviations expanded, never inferred by stripping mascots.
 * Texas A&M retains the institution's proper name (A&M is part of that name).
 */
const NCAAF_SCHOOL_NAMES: Readonly<Record<string, string>> = {
  ACU: "Abilene Christian",
  AFA: "Air Force",
  AKR: "Akron",
  ALA: "Alabama",
  ALCN: "Alcorn State",
  APP: "Appalachian State",
  APSU: "Austin Peay",
  ARIZ: "Arizona",
  ARK: "Arkansas",
  ARMY: "Army",
  ARST: "Arkansas State",
  ASU: "Arizona State",
  AUB: "Auburn",
  BALL: "Ball State",
  BAY: "Baylor",
  BC: "Boston College",
  BGSU: "Bowling Green",
  BOIS: "Boise State",
  BRY: "Bryant",
  BUFF: "Buffalo",
  BYU: "Brigham Young",
  CAL: "California",
  CCU: "Coastal Carolina",
  CHSO: "Charleston Southern",
  CIN: "Cincinnati",
  CIT: "The Citadel",
  CLEM: "Clemson",
  CLT: "Charlotte",
  CMU: "Central Michigan",
  COLO: "Colorado",
  CONN: "Connecticut",
  CSU: "Colorado State",
  DEL: "Delaware",
  DUKE: "Duke",
  DUQ: "Duquesne",
  ECU: "East Carolina",
  EKU: "Eastern Kentucky",
  EMU: "Eastern Michigan",
  FAU: "Florida Atlantic",
  FIU: "Florida International",
  FLA: "Florida",
  FOR: "Fordham",
  FRES: "Fresno State",
  FSU: "Florida State",
  FUR: "Furman",
  GASO: "Georgia Southern",
  GAST: "Georgia State",
  GT: "Georgia Institute of Technology",
  HAMP: "Hampton",
  HAW: "Hawai'i",
  HCU: "Houston Christian",
  HOU: "Houston",
  IDST: "Idaho State",
  ILL: "Illinois",
  IOWA: "Iowa",
  ISU: "Iowa State",
  IU: "Indiana",
  JMU: "James Madison",
  JVST: "Jacksonville State",
  KENN: "Kennesaw State",
  KENT: "Kent State",
  KSU: "Kansas State",
  KU: "Kansas",
  LAF: "Lafayette",
  LAM: "Lamar",
  LIB: "Liberty",
  LOU: "Louisville",
  LSU: "Louisiana State",
  LT: "Louisiana Tech",
  "M-OH": "Miami (Ohio)",
  MASS: "Massachusetts",
  MD: "Maryland",
  ME: "Maine",
  MEM: "Memphis",
  MERC: "Mercyhurst",
  MIA: "Miami (Florida)",
  MICH: "Michigan",
  MINN: "Minnesota",
  MISS: "Mississippi",
  MIZ: "Missouri",
  MORG: "Morgan State",
  MOST: "Missouri State",
  MRSH: "Marshall",
  MSST: "Mississippi State",
  MSU: "Michigan State",
  MTSU: "Middle Tennessee State",
  MUR: "Murray State",
  MVSU: "Mississippi Valley State",
  NAU: "Northern Arizona",
  NAVY: "Navy",
  NCSU: "North Carolina State",
  ND: "Notre Dame",
  NDSU: "North Dakota State",
  NEB: "Nebraska",
  NEV: "Nevada",
  NICH: "Nicholls State",
  NIU: "Northern Illinois",
  NMSU: "New Mexico State",
  NORF: "Norfolk State",
  NU: "Northwestern",
  NWST: "Northwestern State",
  ODU: "Old Dominion",
  OHIO: "Ohio",
  OKST: "Oklahoma State",
  ORE: "Oregon",
  ORST: "Oregon State",
  OSU: "Ohio State",
  OU: "Oklahoma",
  PITT: "Pittsburgh",
  PRST: "Portland State",
  PSU: "Pennsylvania State",
  PUR: "Purdue",
  RGV: "University of Texas Rio Grande Valley",
  RICE: "Rice",
  RUTG: "Rutgers",
  SAC: "Sacramento State",
  SC: "South Carolina",
  SDST: "South Dakota State",
  SDSU: "San Diego State",
  SELA: "Southeastern Louisiana",
  SEMO: "Southeast Missouri State",
  SHSU: "Sam Houston State",
  SJSU: "San Jose State",
  SMU: "Southern Methodist",
  STAN: "Stanford",
  SYR: "Syracuse",
  "TA&M": "Texas A&M University",
  TAR: "Tarleton State",
  TCU: "Texas Christian",
  TEM: "Temple",
  TENN: "Tennessee",
  TEX: "Texas",
  TLSA: "Tulsa",
  TNST: "Tennessee State",
  TOL: "Toledo",
  TOW: "Towson",
  TROY: "Troy",
  TTU: "Texas Tech",
  TULN: "Tulane",
  TXST: "Texas State",
  UAB: "University of Alabama at Birmingham",
  UCF: "University of Central Florida",
  UCLA: "University of California, Los Angeles",
  UGA: "Georgia",
  UK: "Kentucky",
  UL: "University of Louisiana at Lafayette",
  ULM: "University of Louisiana at Monroe",
  UNA: "North Alabama",
  UNC: "North Carolina",
  UNH: "New Hampshire",
  UNLV: "University of Nevada, Las Vegas",
  UNM: "New Mexico",
  UNT: "North Texas",
  URI: "Rhode Island",
  USA: "South Alabama",
  USC: "Southern California",
  USF: "South Florida",
  USM: "Southern Mississippi",
  USU: "Utah State",
  UTAH: "Utah",
  UTEP: "University of Texas at El Paso",
  UTSA: "University of Texas at San Antonio",
  UTU: "Utah Tech",
  UVA: "Virginia",
  VAN: "Vanderbilt",
  VMI: "Virginia Military Institute",
  VT: "Virginia Polytechnic Institute and State University",
  WAKE: "Wake Forest",
  WASH: "Washington",
  WIS: "Wisconsin",
  WKU: "Western Kentucky",
  WMU: "Western Michigan",
  WSU: "Washington State",
  WVU: "West Virginia",
  WYO: "Wyoming",
  YSU: "Youngstown State",
};

/** Display only: callers must keep their canonical code for IDs and helmet lookup. */
export function ncaafSchoolName(code: string): string {
  const normalizedCode = code.trim().toUpperCase();
  return (
    NCAAF_SCHOOL_NAMES[normalizedCode] ?? (normalizedCode || "Unknown school")
  );
}
